# Generated by Django 5.2.17 on 2026-08-08 21:47

from django.db import migrations, models


def populate_keys(apps, schema_editor):
    """Fill both derived keys for records that already exist.

    Historical models carry no save() override, so the keys are computed here
    and written in bulk.
    """
    from tables.search import fold, sort_key

    for model_name, source in (
        ("Author", "name"),
        ("Place", "name"),
        ("Category", "name"),
        ("Image", "title"),
    ):
        model = apps.get_model("tables", model_name)
        rows = []
        for obj in model.objects.all().iterator():
            value = getattr(obj, source, "")
            obj.search_key = fold(value)
            obj.sort_key = sort_key(value)
            rows.append(obj)
        if rows:
            model.objects.bulk_update(rows, ["search_key", "sort_key"], batch_size=500)


def clear_keys(apps, schema_editor):
    """Reverse step: the schema operations drop the columns anyway."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('sort_key',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_key',)},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('author__sort_key', 'sort_key')},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('sort_key',)},
        ),
        migrations.AddField(
            model_name='author',
            name='search_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='sort_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='search_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='search_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='sort_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='search_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='sort_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.RunPython(populate_keys, clear_keys),
    ]
