# Generated by Django 5.1.6 on 2026-08-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('sort_key',)},
        ),
    ]
